language: go

go:
  - 1.10.x

services:
  - postgresql

cache:
  yarn: true
  directories:
  - "$HOME/google-cloud-sdk/"

env:
  global:
    TEDDYCARE_SQL_DIR=$GOPATH/src/github.com/Vinubaba/SANTC-API/api/sql
    BUCKET_SERVICE_ACCOUNT_PATH=/tmp/bucket-service-account-key.json

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - echo $BUCKET_SERVICE_ACCOUNT > /tmp/bucket-service-account-key.json
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

script:
  - ginkgo -r -cover
  - for f in `find . -name "*.coverprofile"`; do cat $f >> teddycare.coverprofile; done;
  - sed -i -e '2,${ /^mode.*atomic/d }' teddycare.coverprofile
  - go tool cover -func=teddycare.coverprofile

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master