language: go

go:
  - 1.10.x

services:
  - postgresql

cache:
  yarn: true
  directories:
  - "$HOME/google-cloud-sdk/"

env:
  global:
    TEDDYCARE_SQL_DIR=$GOPATH/src/github.com/Vinubaba/SANTC-API/sql
    BUCKET_SERVICE_ACCOUNT_PATH=/tmp/bucket-service-account-key.json

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - echo $BUCKET_SERVICE_ACCOUNT > /tmp/bucket-service-account-key.json
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

script:
  - ginkgo -r -cover
  - for f in `find . -name "*.coverprofile"`; do cat $f >> teddycare.coverprofile; done;
  - sed -i -e '2,${ /^mode.*atomic/d }' teddycare.coverprofile
  - go tool cover -func=teddycare.coverprofile

build:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - echo $KUBERNETES_SERVICE_ACCOUNT > /tmp/kubernetes-service-account-key.json
  - gcloud auth activate-service-account --key-file /tmp/kubernetes-service-account-key.json
  - gcloud config set project $GCP_PROJECT
  - gcloud config set compute/zone europe-west1-d
  - gcloud container builds submit . --tag gcr.io/$GCP_PROJECT/teddycare:$TRAVIS_COMMIT

#deploy:
#  - provider: script
#    script:
#      - echo $KUBERNETES_SERVICE_ACCOUNT > /tmp/kubernetes-service-account-key.json
#      - gcloud auth activate-service-account --key-file /tmp/kubernetes-service-account-key.json
#      - gcloud config set project $GCP_PROJECT
#      - gcloud container clusters get-credentials $KUBERNETES_CLUSTER_NAME --region $KUBERNETES_CLUSTER_REGION --project $GCP_PROJECT
#      - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account-key.json
#      -
#    skip_cleanup: true