apiVersion: apps/v1
kind: Deployment
metadata:
  name: teddycare
  labels:
    app: teddycare
spec:
  replicas: 1
  selector:
      matchLabels:
        app: teddycare
  template:
    metadata:
      labels:
        app: teddycare
    spec:
      volumes:
      - name: bucket-service-account
        configMap:
          name: bucket-service-account
      - name: firebase-service-account
        configMap:
          name: firebase-service-account
      - name: cloudsql-instance-sa
        secret:
          secretName: cloudsql-instance-sa
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=teddycare-193910:europe-west1:teddycare-postgresql=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-sa
            mountPath: /secrets/cloudsql
            readOnly: true
      - name: teddycare
        image: gcr.io/teddycare-193910/teddycare:1342
        volumeMounts:
          - name: bucket-service-account
            mountPath: /opt/teddycare/bucket-service-account
            readOnly: true
          - name: firebase-service-account
            mountPath: /opt/teddycare/firebase-service-account
            readOnly: true
        ports:
        - name: test-auth
          containerPort: 8082
          protocol: TCP
        - name: app
          containerPort: 8083
          protocol: TCP
        env:
          - name: TEDDYCARE_PG_USERNAME
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: TEDDYCARE_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
          - name: TEDDYCARE_PG_CONTACT_POINT
            value: "127.0.0.1"
          - name: TEDDYCARE_PG_CONTACT_PORT
            value: "5432"
          - name: TEDDYCARE_PG_DBNAME
            value: "teddycare"
          - name: TEDDYCARE_GCP_PROJECT_ID
            value: "teddycare-193910"
          - name: TEDDYCARE_BUCKET_IMAGES_NAME
            value: "teddycare-images"
          - name: TEDDYCARE_BUCKET_SERVICE_ACCOUNT
            value: "/opt/teddycare/bucket-service-account/adm-bucket-sa.json"
          - name: TEDDYCARE_FIREBASE_SERVICE_ACCOUNT
            value: "/opt/teddycare/firebase-service-account/adm-firebase-sa.json"
          - name: TEDDYCARE_TEST_AUTH_MODE
            value: "true"
          - name: TEDDYCARE_SQL_MIGRATIONS_SOURCE_DIR
            value: "/go/migrations/sql"
          - name: TEDDYCARE_STARTUP_MIGRATION
            value: "true"